// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.data.AddDbContex;

#nullable disable

namespace Web.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Web.data.Models.Davlatlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nomi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Qita_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Qita_Id");

                    b.ToTable("Davlatlar");
                });

            modelBuilder.Entity("Web.data.Models.Qita", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Nomi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Qita");
                });

            modelBuilder.Entity("Web.data.Models.Shaharlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Davlat_id")
                        .HasColumnType("int");

                    b.Property<string>("Nomi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Davlat_id");

                    b.ToTable("Shaharlar");
                });

            modelBuilder.Entity("Web.data.Models.Davlatlar", b =>
                {
                    b.HasOne("Web.data.Models.Qita", "qita")
                        .WithMany("Davlat")
                        .HasForeignKey("Qita_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("qita");
                });

            modelBuilder.Entity("Web.data.Models.Shaharlar", b =>
                {
                    b.HasOne("Web.data.Models.Davlatlar", "Davlat")
                        .WithMany("shahar")
                        .HasForeignKey("Davlat_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Davlat");
                });

            modelBuilder.Entity("Web.data.Models.Davlatlar", b =>
                {
                    b.Navigation("shahar");
                });

            modelBuilder.Entity("Web.data.Models.Qita", b =>
                {
                    b.Navigation("Davlat");
                });
#pragma warning restore 612, 618
        }
    }
}
